-- MySQL Script generated by MySQL Workbench
-- Sat Mar 30 15:57:44 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema controledeyaulas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema controledeyaulas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controledeyaulas` DEFAULT CHARACTER SET utf8 ;
USE `controledeyaulas` ;

-- -----------------------------------------------------
-- Table `controledeyaulas`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controledeyaulas`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NOT NULL,
  `foto` VARCHAR(90) NULL,
  `email` VARCHAR(90) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controledeyaulas`.`jogos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controledeyaulas`.`jogos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NULL,
  `descricao` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controledeyaulas`.`fases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controledeyaulas`.`fases` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `jogos_id` INT NOT NULL,
  `nome` VARCHAR(90) NULL,
  `seqfase` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fases_jogos1_idx` (`jogos_id` ASC)  ,
  CONSTRAINT `fk_fases_jogos1`
    FOREIGN KEY (`jogos_id`)
    REFERENCES `controledeyaulas`.`jogos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controledeyaulas`.`administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controledeyaulas`.`administradores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NULL,
  `email` VARCHAR(90) NULL,
  `senha` VARCHAR(90) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controledeyaulas`.`jogosdousuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controledeyaulas`.`jogosdousuario` (
  `usuarios_id` INT NOT NULL,
  `jogos_id` INT NOT NULL,
  `highscore` DOUBLE NULL,
  `tempodejogo` DOUBLE NULL,
  PRIMARY KEY (`usuarios_id`, `jogos_id`),
  INDEX `fk_usuarios_has_jogos_jogos1_idx` (`jogos_id` ASC)  ,
  INDEX `fk_usuarios_has_jogos_usuarios1_idx` (`usuarios_id` ASC)  ,
  CONSTRAINT `fk_usuarios_has_jogos_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `controledeyaulas`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_jogos_jogos1`
    FOREIGN KEY (`jogos_id`)
    REFERENCES `controledeyaulas`.`jogos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controledeyaulas`.`itensjogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controledeyaulas`.`itensjogo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fases_id` INT NOT NULL,
  `nome` VARCHAR(90) NULL,
  `foto` VARCHAR(90) NULL,
  `pontuacao` DECIMAL NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_itens_jogo_fases1_idx` (`fases_id` ASC)  ,
  CONSTRAINT `fk_itens_jogo_fases1`
    FOREIGN KEY (`fases_id`)
    REFERENCES `controledeyaulas`.`fases` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controledeyaulas`.`itensjogodousuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controledeyaulas`.`itensjogodousuario` (
  `itensjogo_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  `jogos_id` INT NOT NULL,
  `quantidade` DECIMAL NULL,
  PRIMARY KEY (`itensjogo_id`, `usuarios_id`, `jogos_id`),
  INDEX `fk_itens_jogo_has_jogosdousuario_jogosdousuario1_idx` (`usuarios_id` ASC, `jogos_id` ASC)  ,
  INDEX `fk_itens_jogo_has_jogosdousuario_itens_jogo1_idx` (`itensjogo_id` ASC)  ,
  CONSTRAINT `fk_itens_jogo_has_jogosdousuario_itens_jogo1`
    FOREIGN KEY (`itensjogo_id`)
    REFERENCES `controledeyaulas`.`itensjogo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itens_jogo_has_jogosdousuario_jogosdousuario1`
    FOREIGN KEY (`usuarios_id` , `jogos_id`)
    REFERENCES `controledeyaulas`.`jogosdousuario` (`usuarios_id` , `jogos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controledeyaulas`.`fasesjogosdousuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controledeyaulas`.`fasesjogosdousuario` (
  `jogosdousuario_usuarios_id` INT NOT NULL,
  `jogosdousuario_jogos_id` INT NOT NULL,
  `fases_id` INT NOT NULL,
  `highscore` DOUBLE NULL,
  `finalizada` TINYINT NULL,
  `disponivel` TINYINT NULL,
  PRIMARY KEY (`jogosdousuario_usuarios_id`, `jogosdousuario_jogos_id`, `fases_id`),
  INDEX `fk_jogosdousuario_has_fases_fases1_idx` (`fases_id` ASC)  ,
  INDEX `fk_jogosdousuario_has_fases_jogosdousuario1_idx` (`jogosdousuario_usuarios_id` ASC, `jogosdousuario_jogos_id` ASC)  ,
  CONSTRAINT `fk_jogosdousuario_has_fases_jogosdousuario1`
    FOREIGN KEY (`jogosdousuario_usuarios_id` , `jogosdousuario_jogos_id`)
    REFERENCES `controledeyaulas`.`jogosdousuario` (`usuarios_id` , `jogos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jogosdousuario_has_fases_fases1`
    FOREIGN KEY (`fases_id`)
    REFERENCES `controledeyaulas`.`fases` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
